APP_NAME="Portfolio Hanif Ibrahim"
APP_ENV=publish
APP_KEY=base64:F/L4vjFmu0mHMj2mONHc/L3NQ8y69c0JEgR5fGjnqx0=
APP_DEBUG=true
APP_URL=https://riachoune.my.id/

APP_LOCALE=id
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=id_ID

APP_MAINTENANCE_DRIVER=file
# APP_MAINTENANCE_STORE=database

# PHP_CLI_SERVER_WORKERS=4

BCRYPT_ROUNDS=12

LOG_CHANNEL=daily
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=ltegvebz_fadilla
DB_USERNAME=ltegvebz_angkara
DB_PASSWORD=NR;g7EO@X(v3C6m8

SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync

CACHE_STORE=file
# CACHE_PREFIX=

MEMCACHED_HOST=127.0.0.1

REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_MAILER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=rouf.pklsampulkreativ@gmail.com
MAIL_PASSWORD="cmma grit vrzn vsih"
MAIL_ENCRYPTION=ssl
MAIL_FROM_ADDRESS="rouf.pklsampulkreativ@gmail.com"
MAIL_FROM_NAME="${APP_NAME}"

# Email tujuan untuk contact form
MAIL_TO_ADDRESS=Fadillatasya5@gmail.com

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

VITE_APP_NAME="${APP_NAME}"
